//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAKClaims.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Adjustor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adjustor()
        {
            this.ClaimActions = new HashSet<ClaimAction>();
            this.Claims = new HashSet<Claim>();
        }
    
        public int AdjustorId { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool IsManager { get; set; }
        public string Password { get; set; }
        public int ManagerId { get; set; }
        public string LoginID { get; set; }
        public Nullable<int> RegionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimAction> ClaimActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Region Region { get; set; }
    }
}
