//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAKClaims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int AttachmentId { get; set; }
        public byte[] Attachment1 { get; set; }
        public string AttachmentName { get; set; }
        public int ClaimId { get; set; }
        public string AttachmentPath { get; set; }
    
        public virtual Claim Claim { get; set; }
    }
}
