//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claims.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClaimsEntities : DbContext
    {
        public ClaimsEntities()
            : base("name=ClaimsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Adjustor> Adjustors { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<ClaimAction> ClaimActions { get; set; }
        public virtual DbSet<Insured> Insureds { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
    }
}
